#!/bin/sh

OUTPUT="/tmp/cmd_output${1}"
flush_output()
{
	echo "" > "$OUTPUT"
}
remove_output()
{
	rm -f "$OUTPUT"
}
SED="/bin/sed"

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
	  . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

echo $wan_main_index > "$OUTPUT"

for wan_idx in `"$SED" -n 's,\,, ,gp' "$OUTPUT"`
do
	eval wan_conn='$'wan_${wan_idx}_connName
	
	if [ "$default_wan_conn_connName" = "$wan_conn" ]; then
		eval link_type='$'wan_${wan_idx}_linkType
		if [ "$link_type" = "4" ]; then # PPPoE
#			echo `/etc/rc.d/get_wan_if $wan_idx`
			. /etc/rc.d/get_wan_if $wan_idx
			echo $WAN_IFNAME
		fi
	fi
done

#def_wan_idx="`echo $default_wan_conn_iface | sed -n 's,ppp,,;1p'`"
#echo $def_wan_idx


