#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

case "$1" in
	start)
		#start
		dhcp_cur_status=`/usr/sbin/status_oper GET udhcpd_config status`
                j=0
		while [ 1 ]
		do  		
		if [ "$dhcp_cur_status" = "complete" -o -z "$dhcp_cur_status" -o "$j" = "3" ]; then
			/usr/sbin/status_oper SET "udhcpd_config" "status" "start"
			break
		else
			sleep 1
			dhcp_cur_status=`/usr/sbin/status_oper GET udhcpd_config status`
		fi
			j=$(( $j + 1 ))		
		done

		. /etc/rc.d/init.d/udhcpd_start
			
		/usr/sbin/status_oper SET "udhcpd_config" "status" "complete"

		# if [ "$CONFIG_FEATURE_INETD" = "1" ]; then
		#	start inetd superserver
		#	. /etc/init.d/inetd restart
		# fi
		

		;;
	stop)
		#stop
		dhcp_cur_status=`/usr/sbin/status_oper GET udhcpd_config status`
                j=0
		while [ 1 ]
		do  		
		if [ "$dhcp_cur_status" = "complete" -o -z "$dhcp_cur_status" -o "$j" = "3" ]; then
			/usr/sbin/status_oper SET "udhcpd_config" "status" "stop"
			break
		else
			sleep 1
			dhcp_cur_status=`/usr/sbin/status_oper GET udhcpd_config status`
		fi
			j=$(( $j + 1 ))		
		done

        # remove the route associated with the default pool
        /usr/sbin/route_util DEL ${lan_dhcps_startIp} ${lan_dhcps_netmask} ${lan_main_0_ipAddr} ${lan_main_0_interface}

        # call script to delete the routes associated with configured conditional pools
       		 . /etc/rc.d/init.d/udhcpd_pool_conf route_del
		#echo "rm -rf /ramdisk/etc/udhcpd.conf /ramdisk/etc/udhcpd_0_*.conf"
       		 #rm -rf /ramdisk/etc/udhcpd.conf /ramdisk/etc/udhcpd_0_*.conf > /tmp/log 2> /tmp/err_log
 
		/usr/sbin/status_oper SET "udhcpd_config" "status" "complete"

		if [ -f /var/run/udhcpd.pid ]; then
			if [ "$lan_main_0_dhcpMode" != "server" -o "$lan_main_0_dhcpMode" != "relay" ]; then
				dwatchctl stop udhcpd
			fi
			. /etc/rc.d/killproc udhcpd
		fi
		# udhcpd now is part of inetd, so it does not have a pid file for it
		# to stop udhcpd do a manual kill
		#killall -9 udhcpd
		#if [ "$CONFIG_FEATURE_INETD" = "1" ]; then
		#	. /etc/init.d/inetd_start
		#fi
			
		;;
	restart)
		#restart
		. /etc/rc.d/init.d/udhcpd_pool_conf route_del
		rm -rf /ramdisk/etc/udhcpd.conf /ramdisk/etc/udhcpd_0_*.conf
		if [ -f /var/run/udhcpd.pid ]; then
			. /etc/rc.d/killproc udhcpd
		fi
		. /etc/rc.d/init.d/udhcpd_start
		;;
	*)
		echo $"Usage $0 {start|stop|restart}"
		#exit 1
esac

