#!/bin/sh /etc/rc.common
# (C) 2008 openwrt.org

START=96

start()
{
	# overwrite vcc frequency
	# io -w -4 0x1DF000BC 0x00000183
	#ln -s /lib/firmware/falcon_voip_fw.bin /lib/firmware/voice_vr9_firmware.bin
	#ln -s /lib/firmware/falcon_voip_fw.bin /lib/firmware/voice_ar9_firmware.bin
	echo start voice demo
}

stop()
{
    echo Stop Voice Demo
}
