#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		. /etc/rc.conf 2>/dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then
	echo "1650_wlan_get_ap_dyn_info ${1}"
	if [ ${1} -gt 0 ]; then
		eval wave100_cpeid='$'wlmn_${1}_cpeId
		if [ ! -f /tmp/wave100_map_wlmn_${wave100_cpeid} ] ; then
			echo ${1} >  /tmp/wave100_map_wlmn_${wave100_cpeid}
		fi
		wave100_if_idx=`cat  /tmp/wave100_map_wlmn_${wave100_cpeid}`
	else 
		wave100_if_idx=0  
	fi
	cat /proc/net/wlan_1650/vap$wave100_if_idx/ap_dyn_info
fi # ]
