#!/bin/sh
# 000001:tc.chen 2005/06/07 add 802.1p and ip ptos support. rewrite all of the qos scirpts
#509025:linmars 2005/09/02 move original vlan related script (vlan/vlan_start/vlan_start) to pif (pif/pif_start/pif_stop)

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi
#000001:tc.chen if [ "$vlan_enable" = "1" ]; then
#000001:tc.chen start
#507271:linmars change from vlan_enable to vb_enable
#509023:linmars start
#if [ "$vb_enable" = "1" -o "$QOS_PRIO" = "1" ]; then
if [ "`/usr/sbin/status_oper GET pif status`" != "start" ]; then 
#	MAC_ADDR_BEGIN=`ifconfig eth0 | grep HWaddr | cut -f11 -d" "`
	MAC_ADDR_BEGIN=`ifconfig eth0`
	MAC_ADDR_BEGIN=${MAC_ADDR_BEGIN%% inet*}
	MAC_ADDR_BEGIN=${MAC_ADDR_BEGIN##*HWaddr }
	insmod ifx_nfext_sw_phyport
	brctl delif br0 eth0

	pindex=4
	while [ "$pindex" -gt 0 ]
	do
		value=$(( 15 + $pindex ))
		#NEW_MAC_ADDR=`echo $MAC_ADDR_BEGIN|/usr/sbin/next_macaddr $value |tr -d ':'`
		NEW_MAC_ADDR=`echo $MAC_ADDR_BEGIN|/usr/sbin/next_macaddr $value`
		pindex=$(( $pindex - 1 ))
		#brctl addif br0 swport$pindex
		if [ "$pindex" = "0" ]; then
			ifconfig swport$pindex hw ether $MAC_ADDR_BEGIN 0.0.0.0 up
		else
			ifconfig swport$pindex hw ether $NEW_MAC_ADDR 0.0.0.0 up
		fi
		brctl addif br0 swport$pindex
	done

#000001:tc.chen start
	/usr/sbin/status_oper SET pif status start
fi
#000001:tc.chen end
#fi
#509023:linmars end
