#!/bin/sh
#509025:linmars 2005/09/02 move original vlan related script (vlan/vlan_start/vlan_start) to pif (pif/pif_start/pif_stop)
#509026:linmars 2005/09/02 add VLAN related script (vlan/vlan_start/vlan_stop)
# 602091:jelly: 2006/02/09 fix vlan bug
#604181:Sumedh - changes in vlanctl (for pbgid) and added vlan_mem status variable

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi


#511048:linmars start
FUNCFILE="/etc/rc.d/init.d/vlan_common.sh"


if [ "`/usr/sbin/status_oper GET vlan status`" = "start" ]; then
	if [ $# -eq 1 ]; then
		. /etc/rc.d/init.d/vlan_common.sh
		wan_idx=$1
		ifname=`$FUNCFILE vbridge_get_ifname $wan_idx`
		if [ "$ifname" != "" ]; then
			cfg=`$FUNCFILE vbridge_get_cfg $wan_idx`
                        /usr/sbin/vlanctl 0 0 $wan_idx $ifname $cfg  #604181:Sumedh
			#/usr/sbin/vlanctl 0 $wan_idx $ifname $cfg
		else
			echo "ERROR!!! Invalid Interface ID: $wan_idx"
		fi
	else
		rmmod ifx_nfext_vbridge
		/usr/sbin/status_oper SET vlan status stop
                /usr/sbin/status_oper SET vlan_mem status stop  #604181:Sumedh
		. /etc/rc.d/init.d/pif stop
	fi
fi
#511048:linmars end
