#!/bin/sh
#604181:Sumedh - this script is used to apply VLAN membership rules

if [ -r /etc/rc.conf ]; then
	 . /etc/rc.conf 2> /dev/null
fi

if [ -r /etc/rc.d/config.sh ]; then
	. /etc/rc.d/config.sh 2>/dev/null
fi

FUNCFILE="/etc/rc.d/init.d/vlan_common.sh"

if [ "$vb_enable" = "1" ]; then
	if [ "`/usr/sbin/status_oper GET vlan_mem status`" != "start" ]; then 
		/usr/sbin/status_oper SET vlan_mem status start
		wan_idx=16
		while [ "$wan_idx" -lt 20 ]
		do
			ifname=`$FUNCFILE vbridge_get_ifname $wan_idx`
			eval vlan_memCount='$'VM_intf$wan_idx"_Count"
			i=0;
			while [ "$vlan_memCount" -a "$i" -lt "$vlan_memCount" ]
			do
				eval vlan_id='$'VM_intf$wan_idx"_ID"$i
				eval vlan_tag='$'VM_intf$wan_idx"_TAG"$i

				/usr/sbin/vlanctl 1 1 $wan_idx $ifname $vlan_id 2 $vlan_tag
				#echo "vlanctl 1 1 $wan_idx $ifname $vlan_id 2 $vlan_tag"
				i=$(( $i + 1 ))
			done
			wan_idx=$(( $wan_idx + 1 ))
		done
	fi

	if [ $# -eq 1 ]; then
		wan_idx=$1
		ifname=`$FUNCFILE vbridge_get_ifname $wan_idx`
		eval vlan_memCount='$'VM_intf$wan_idx"_Count"
		i=0;
		while [ "$vlan_memCount" -a "$i" -lt "$vlan_memCount" ]
		do
			eval vlan_id='$'VM_intf$wan_idx"_ID"$i
			eval vlan_tag='$'VM_intf$wan_idx"_TAG"$i

			/usr/sbin/vlanctl 1 1 $wan_idx $ifname $vlan_id 2 $vlan_tag
			#echo "vlanctl 1 1 $wan_idx $ifname $vlan_id 2 $vlan_tag"
			i=$(( $i + 1 ))
		done
	else
		wan_idx=1
		while [ "$wan_idx" -lt 16 ]
		do
            eval link_type='$'wan_${wan_idx}_linkType
            if [ "$link_type" = "1" ]; then # EoATM
                eval addr_type='$'wanip_${wan_idx}_addrType
                if [ "$addr_type" = "0" ]; then # Bridge Mode
                    wan_type="BRIDGE"
                fi
            else
                wan_type=""
            fi

			case "$wan_type" in
				[Bb][Rr][Ii][Dd][Gg][Ee])
					ifname=`$FUNCFILE vbridge_get_ifname $wan_idx`
					if [ "$ifname" != "" ]; then
						eval vlan_memCount='$'VM_intf$wan_idx"_Count"
						i=0;
						while [ "$vlan_memCount" -a "$i" -lt "$vlan_memCount" ]
						do
							eval vlan_id='$'VM_intf$wan_idx"_ID"$i
							eval vlan_tag='$'VM_intf$wan_idx"_TAG"$i

							/usr/sbin/vlanctl 1 1 $wan_idx $ifname $vlan_id 2 $vlan_tag
							#echo "vlanctl 1 1 $wan_idx $ifname $vlan_id 2 $vlan_tag"
							i=$(( $i + 1 ))
						done
					else
						echo "ERROR!!! Invalid Interface ID: $wan_idx"
					fi
				;;

				*)
				;;
			esac
			
			wan_idx=$(( $wan_idx + 1 ))
		done
	fi 
fi
