deps_config := \
	package/uboot-lantiq/Config.in \
	package/feeds/ltq_feeds_uboot/open_uboot/config/common/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/lib/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/board/vbg400/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/board/ar10/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/board/hn1/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/board/vr9/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/board/amazon_se/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/board/danube/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/board/ar9/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/scripts_platform/Kconfig \
	package/feeds/ltq_feeds_uboot/open_uboot/config/Kconfig \
	package/hostapd/Config.in \
	package/feeds/open_applications/samba3/Config.in \
	package/feeds/ltq_feeds_upnpdm/upnpdm/config/Config.in \
	package/ltq-tapidemo/Config.in \
	package/kexec-tools/Config.in \
	package/madwifi/Config.in \
	package/ltq-vmmc/Config.in \
	package/ltq-tapi/Config.in \
	package/compcache/Config.in \
	package/ar7-atm/Config.in \
	package/ltq-dsl/Config.in \
	package/libpcap/Config.in \
	package/feeds/open_multimedia/ffmpeg/Config.in \
	package/feeds/open_applications/openssl/Config.in \
	package/feeds/ltq_voice_cpe/teridian-voice-daa-ter1x66/config/Config.in \
	package/feeds/ltq_feeds_ethsw/lq-ethsw-cli/config/Config.in \
	package/feeds/ltq_feeds_wave/lq-wave-300/config/Config.in \
	package/feeds/ltq_feeds_wave_mbssid/lq-wave100/config/Config.in \
	package/feeds/ltq_feeds_coc/lq-coc-app-pmd/config/Config.in \
	package/feeds/ltq_feeds_coc/lq-coc-app-pm/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-wineasy/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-vmmc-coef-ar10/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-vmmc-coef-vr9/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-vmmc-coef-ar9/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-vmmc/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-tapidump/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-tapidemo/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-tapi-duslic_xt-coef/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-tapi-duslic_xt/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-tapi-lib-nlt/config/Config.in \
	package/feeds/ltq_voice_cpe/ifx-voice-cpe-tapi/config/Config.in \
	package/feeds/ltq_feeds_ethsw/ifx-ethsw/config/Config.in \
	package/feeds/ltq_dsl_cpe/ifx-dsl-cpe-mei-vrx/Config.in \
	package/feeds/ltq_dsl_cpe/ifx-dsl-cpe-mei-danube/Config.in \
	package/feeds/ltq_dsl_cpe/ifx-dsl-cpe-control-vrx/Config.in \
	package/feeds/ltq_dsl_cpe/ifx-dsl-cpe-control-danube/Config.in \
	package/feeds/ltq_dsl_cpe/ifx-dsl-cpe-api-vrx/Config.in \
	package/feeds/ltq_dsl_cpe/ifx-dsl-cpe-api-danube/Config.in \
	package/feeds/ltq_feeds_devm_cpe/ifx_devm/config/Config.in \
	package/feeds/ltq_feeds_dect/ifx_voip/config/Config.in.voip \
	package/feeds/ltq_feeds_dect/ifx_dect/config/Config.in.dect \
	package/feeds/ltq_feeds_netcomp_cpe/lq_igmpd/config/Config.in \
	package/feeds/ltq_feeds_netcomp_cpe/ifx_utilities/config/Config.in \
	package/feeds/ltq_feeds_netcomp_cpe/ifx_oam/config/Config.in \
	package/feeds/ltq_feeds_netcomp_cpe/ifx_httpd/config/Config.in \
	package/feeds/ltq_feeds_netcomp_cpe/ifx_config_common_features/config/Config.in \
	package/feeds/ltq_feeds_netcomp_cpe/ifx_IFXAPIs/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-voicedemo/Config.in \
	package/feeds/ltq_gpon_onu/gpon-sipdemo/Config.in \
	package/feeds/ltq_gpon_onu/gpon-sfp/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-rpc/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-onu-firmware/config/Config.optic \
	package/feeds/ltq_gpon_onu/gpon-optic-drv/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-onu-firmware/config/Config.onu \
	package/feeds/ltq_gpon_onu/gpon-onu-firmware/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-omci-onu-ocs/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-omci-onu/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-omci-api/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-ocal/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-onu-drv/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-flow-api/config/Config.in \
	package/feeds/ltq_gpon_onu/gpon-dti-agent/config/Config.in \
	package/feeds/ltq_common/lib-cli/config/Config.in \
	package/udev/Config.in \
	package/feeds/open_applications/busybox/config/sysklogd/Config.src \
	package/feeds/open_applications/busybox/config/shell/Config.src \
	package/feeds/open_applications/busybox/config/selinux/Config.src \
	package/feeds/open_applications/busybox/config/runit/Config.src \
	package/feeds/open_applications/busybox/config/procps/Config.src \
	package/feeds/open_applications/busybox/config/mailutils/Config.src \
	package/feeds/open_applications/busybox/config/printutils/Config.src \
	package/feeds/open_applications/busybox/config/networking/udhcp/Config.src \
	package/feeds/open_applications/busybox/config/networking/Config.src \
	package/feeds/open_applications/busybox/config/miscutils/Config.src \
	package/feeds/open_applications/busybox/config/util-linux/Config.src \
	package/feeds/open_applications/busybox/config/modutils/Config.src \
	package/feeds/open_applications/busybox/config/e2fsprogs/Config.src \
	package/feeds/open_applications/busybox/config/loginutils/Config.src \
	package/feeds/open_applications/busybox/config/init/Config.src \
	package/feeds/open_applications/busybox/config/findutils/Config.src \
	package/feeds/open_applications/busybox/config/editors/Config.src \
	package/feeds/open_applications/busybox/config/debianutils/Config.src \
	package/feeds/open_applications/busybox/config/console-tools/Config.src \
	package/feeds/open_applications/busybox/config/coreutils/Config.src \
	package/feeds/open_applications/busybox/config/archival/Config.src \
	package/feeds/open_applications/busybox/config/libbb/Config.src \
	package/feeds/open_applications/busybox/config/Config.in \
	package/feeds/open_applications/br2684ctl/config/Config.in \
	package/block-extroot/Config.in \
	package/base-files/image-config.in \
	tmp/.config-package.in \
	target/toolchain/Config.in \
	target/sdk/Config.in \
	target/imagebuilder/Config.in \
	toolchain/uClibc/Config.version \
	toolchain/glibc/Config.version \
	toolchain/eglibc/Config.version \
	toolchain/gcc/Config.version \
	toolchain/uClibc/Config.in \
	toolchain/glibc/Config.in \
	toolchain/eglibc/config/Config.in \
	toolchain/eglibc/Config.in \
	toolchain/gcc/Config.in \
	toolchain/binutils/Config.in \
	toolchain/Config.in \
	target/linux/lantiq/image/Config.in \
	target/linux/ltqcpe/image/Config.in \
	tmp/.config-target.in \
	target/Config.in \
	/home/vince/VOLTE-code/trunk/Config.in.temp

include/config/auto.conf: \
	$(deps_config)


$(deps_config): ;
