#!/bin/sh

wanMode=0

if [ "$1" = "0" ]; then
	if [ "$2" = "0" ]; then # ADSL and ATM
		wanMode=0
	elif [ "$2" = "1" ]; then # ADSL and PTM
		wanMode=3
	fi
elif [ "$1" = "3" ]; then
	if [ "$2" = "0" ]; then # VDSL and ATM
		wanMode=5
	elif [ "$2" = "1" ]; then # VDSL and PTM
		wanMode=4
	fi
elif [ "$1" = "1" ]; then
	wanMode=1
elif [ "$1" = "2" ]; then # Eth on MII1
	wanMode=2
elif [ "$1" = "5" ]; then # 3G
	wanMode=6
elif [ "$1" = "6" ]; then  #LTE
        wanMode=7
fi

