#!/bin/sh

case "$1" in
	start)
		#start
		shift
		. /etc/rc.d/init.d/pppoe_start $@
		;;
	stop)
		#stop
		shift
		. /etc/rc.d/init.d/pppoe_stop $@
		;;
	restart)
		#restart
		shift
		. /etc/rc.d/init.d/pppoe_stop $@
		. /etc/rc.d/init.d/pppoe_start $@
		;;
	*)
		echo $"Usage $0 {start|stop|restart}"
		#exit 1
esac

#exit $?
