#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
       . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

wan_idx=`cat /etc/rc.conf | grep "ifppp=\"${2}\"" | cut -d '_' -f 2`


case "$1" in 
      start)
               . /etc/rc.d/create_and_run_dhcp6c_cfg start $2 $wan_idx
      ;;
      stop)
               . /etc/rc.d/create_and_run_dhcp6c_cfg stop $2 $wan_idx
      ;;
esac   
