#!/bin/sh

#start() {
#	/usr/sbin/zebra -f /etc/zebra.conf -d
# Generate Settings for some demands from system configuration file
#/etc/ripd.conf
if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

if [ "$route_dynamic_fEnable" = "1" ]; then
  if [ -s /etc/ripd.conf -o -f /etc/ripd.conf ]; then
	case $route_dynamic_supplyMode in
	     0) echo "RIP down";;
		 1|2)
			if [ $# -eq 1 ]; then
				. /etc/rc.d/init.d/create_rip_config "$route_dynamic_supplyMode" "$1"
			else
				. /etc/rc.d/init.d/create_rip_config "$route_dynamic_supplyMode"
			fi
			;;
		 *)
			if [ $# -eq 1 ]; then
				. /etc/rc.d/init.d/create_rip_config "1" "$1"
			else
				. /etc/rc.d/init.d/create_rip_config "1"
			fi
			;;
        esac
  fi

	#naptcfg --Servicesinit
	sleep 1
	/usr/sbin/ripd -f /etc/ripd.conf -d
fi
#}
