#!/bin/sh
OUTPUT="/tmp/cmd_output20"
flush_output()
{
	echo "" > "$OUTPUT"
}
remove_output()
{
	rm -f "$OUTPUT"
}
SED="/bin/sed"

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ -r /etc/rc.d/config.sh ]; then
	. /etc/rc.d/config.sh 2>/dev/null
fi

#/etc/rc.d/init.d/adsl_link_status_update 0

. /etc/rc.d/common_func.sh

if [ "$CONFIG_FEATURE_LED" = "1" ]; then
	echo none > /sys/class/leds/broadband_led/trigger
	echo 0 > /sys/class/leds/broadband_led/brightness
	echo none > /sys/class/leds/internet_led/trigger
	echo 0 > /sys/class/leds/internet_led/brightness
fi	
if [ "$CONFIG_FEATURE_LED_INTERNET_RED" = "1" ]; then
	echo none > /sys/class/leds/internet_red_led/trigger
	echo 0 > /sys/class/leds/internet_red_led/brightness
fi	

#706121 start - set status down and raise link down event
echo "0" > /tmp/adsl_status

flush_output

# call event utility for adsl link up
/usr/sbin/ifx_event_util "ADSL_LINK" "DOWN"
/usr/sbin/ifx_event_util "WAN" "STOP" &
#706121 end

remove_output
