#!/bin/sh
if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

#WAN="`/etc/rc.d/get_wan_if $1`"
. /etc/rc.d/get_wan_if $1
WAN=$WAN_IFNAME

iptables -t mangle -D QOS_POSTROUTING -o $WAN -j IMQ --todev 2
#downstram
iptables -t mangle -D QOS_PREROUTING -i $WAN -j IMQ --todev 0
