#!/bin/sh

# 000001:tc.chen start
if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

iptables -t mangle -D PREROUTING -j QOS_PREROUTING
iptables -t mangle -D POSTROUTING -j QOS_POSTROUTING

# IMQ device name
DS_DEV_0=imq0
DS_DEV_1=imq1
DS_DEV_2=imq2

	ifconfig $DS_DEV_0 down
	ifconfig $DS_DEV_1 down
	ifconfig $DS_DEV_2 down
	tc qdisc del dev $DS_DEV_0 root
	tc qdisc del dev $DS_DEV_1 root
	tc qdisc del dev $DS_DEV_2 root
	rmmod imq

/usr/sbin/status_oper SET qos status stop

# 507141:tc.chen update netfilter flag to enable/disable netfilter module
/usr/sbin/naptcfg --UpdateNetfilterFlag

#exit $?
