#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

#LAN="`/etc/rc.d/get_lan_if`"
. /etc/rc.d/get_lan_if
LAN=$LAN_IFNAME

	if [ "$DIFFSERV_VIRTUAL_SERVER" = "1" ]; then
		iptables -t mangle -A PREROUTING -i $LAN -j IMQ --todev 2
		i=0
		while [ "$i" -lt $nat_virtualser_Count ]
		do
			eval NATVS_PTYPE='$'nat_virtualser_${i}_ptype
			if [ "$NATVS_PTYPE" = "1" ]; then
				NATVS_PTYPE="tcp"
			elif [ "$NATVS_PTYPE" = "2" ]; then
				NATVS_PTYPE="udp"
			else
				NATVS_PTYPE="all"
			fi
			eval NATVS_PIP='$'nat_virtualser_${i}_privateIp
			eval NATVS_PPORT='$'nat_virtualser_${i}_pport
			eval NATVS_F='$'nat_virtualser_${i}_fEnable
			eval NATVS_QOS_ENABLE='$'nat_virtualser_${i}_upqosEnable
			if [ "$NATVS_F" = "1" -a "$NATVS_QOS_ENABLE" = "1" ]; then
				iptables -t mangle -I PREROUTING -i $LAN -s ${NATVS_PIP} -p ${NATVS_PTYPE} --sport ${NATVS_PPORT} -j MARK --set-mark ${i}
			fi
			i=$(( $i + 1 ))
		done
	fi
