#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

# delete mopa interface
# delete_mpoa_if if_index

if [ $# = 2 ]; then
	/sbin/ifconfig ${1}.${2} down
	/sbin/vconfig rem ${1}.${2}

	# Remove WAN interface from PPA
	. /etc/rc.d/ppa_config.sh delwan ${1}.${2}

	# TBD : status update needs to happen
else
	# TBD : references of VCChannel to be replaced by vlanch
	eval vcEna='$'VCChannel_${1}_fEnable
	if [ -n "$vcEna" -a "$vcEna" = "1" ]; then
		eval nas_iface='$'VCChannel_${1}_l2ifName
		/sbin/ifconfig $nas_iface down
		#. /etc/rc.d/killproc $nas_iface
		nas_idx=${nas_iface##nas}
		/usr/sbin/br2684ctl -k $nas_idx

		# Remove WAN interface from PPA
		. /etc/rc.d/ppa_config.sh delwan ${nas_iface}

		#/usr/sbin/status_oper SET VCChannel${1}_Info VCC "$adsl_vcc" STATUS DISCONNECTED
		/usr/sbin/status_oper SET VCChannel${1}_Info STATUS DISCONNECTED
	fi
fi
