#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

# delete clip interface
# delete_clip_if if_index DEFAULT_ROUTE

	eval atm_iface='$'wanip_${1}_ifatm
	/sbin/ifconfig $atm_iface down
	/usr/sbin/atmarp -D $atm_iface
	/usr/sbin/atmarp -d $2

	eval VCC_SETTING='$'wanip_${1}_l2ifName
	i=0
	while [ $i -lt $adsl_vcchannel_Count ]; do
		eval adsl_vcc='$'VCChannel_${i}_l2ifName
		if [ "A$adsl_vcc" = "A$VCC_SETTING" ]; then
			break
		fi
		i=`expr $i + 1`
	done
	i=`expr $i + 1`
	/usr/sbin/status_oper SET VCChannel${i}_Info VCC "$adsl_vcc" STATUS DISCONNECTED
