#!/bin/sh
# To be invoked with create_rip_config <rip version (1|2)>

if [ ! "$ENVLOADED" ]; then
        if [ -r /etc/rc.conf ]; then
                 . /etc/rc.conf 2> /dev/null
                ENVLOADED="1"
        fi
fi

if [ ! "$CONFIGLOADED" ]; then
        if [ -r /etc/rc.d/config.sh ]; then
                . /etc/rc.d/config.sh 2>/dev/null
                CONFIGLOADED="1"
        fi
fi

OUTPUT="/tmp/cmd_output"
flush_output()
{
          echo "" > "$OUTPUT"
}
SED="/bin/sed"

echo '!' > /var/zebra.conf
echo "hostname ltqcpe" >> /var/zebra.conf
echo "password zebra" >> /var/zebra.conf
echo "enable password zebra" >> /var/zebra.conf

