#!/bin/sh
if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
	 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

	if [ "$ALG_SIP_ENABLE" = "1" ]; then
		/usr/sbin/nfappcfg sip disable

	fi
		/usr/sbin/nfappcfg netmeeting disable
		/usr/sbin/nfappcfg rtsp disable 
		/usr/sbin/nfappcfg ipsec disable 
		/usr/sbin/nfappcfg ftp disable 
		/usr/sbin/nfappcfg pptp disable 

#		/etc/rc.d/init.d/disable_voip
#		/etc/rc.d/init.d/enable_voip

