#!/bin/sh
if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
	 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

	if [ $ALG_SIP_ENABLE = "1" ]; then
		/usr/sbin/nfappcfg sip enable -tudp -p$ALG_SIP_PORT -b
#		. /etc/rc.d/init.d/disable_voip
#	else
#		. /etc/rc.d/init.d/disable_voip
#		. /etc/rc.d/init.d/enable_voip
	fi

	if [ $NETMEETING_STATUS = "1" ]; then
		/usr/sbin/nfappcfg netmeeting enable
	fi

	if [ $RTSP_STATUS = "1" ]; then
		/usr/sbin/nfappcfg rtsp enable 
	fi

	if [ $IPSEC_STATUS = "1" ]; then
		/usr/sbin/nfappcfg ipsec enable 
	fi

	if [ $FTP_STATUS = "1" ]; then
		/usr/sbin/nfappcfg ftp enable 
	fi

	if [ $PPTP_STATUS = "1" ]; then
		/usr/sbin/nfappcfg pptp enable 
	fi


