#!/bin/sh
if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
	 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

case "$1" in 
	start)
		#start
		shift
		. /etc/rc.d/init.d/ddns_start
		;;
	stop)
		#stop
		shift
		. /etc/rc.d/init.d/ddns_stop
		;;
	restart)
		shift
		. /etc/rc.d/init.d/ddns_stop
		. /etc/rc.d/init.d/ddns_start
		;;
	*)
		echo $"Usage $0 {start|stop|restart}"
		# exit 1
esac

#exit $?

