#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

#start() {
#	if [ $NTP_Client = "1" ]; then
#		if [ $NTP_Server != "0" ]; then
#			/usr/sbin/ntpclient -s -h ${NTP_Server} -o ${time_minute_offset} &
#		fi
#	fi
#}
#
#stop() {
#	# get ntpclient process id and kill it
#	for NTP_Client_PID in `ps|grep ntpclient |cut -c 1-5`
#	do
#		kill -9 $NTP_Client_PID
#	done
#}
#
#restart() {
#	stop
#	start
#}

case "$1" in
	start)
		#start
		shift
		#/etc/rc.d/init.d/ntpc_start $@
		. /etc/rc.d/init.d/ntpc_start
		;;
	stop)
		#stop
		shift
		#/etc/rc.d/init.d/ntpc_stop $@
		. /etc/rc.d/init.d/ntpc_stop 
		;;
	restart)
		#restart
		shift
		#/etc/rc.d/init.d/ntpc_stop $@
		#/etc/rc.d/init.d/ntpc_start $@
		. /etc/rc.d/init.d/ntpc_stop
		. /etc/rc.d/init.d/ntpc_start 
		;;
	*)
		echo $"Usage $0 {start|stop|restart}"
		#exit 1
esac

#exit $?
