#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

#stop() {
	# get ntpclient process id and kill it
		for NTP_Client_PID in `ps|grep ntpclient |cut -c 1-5`
		do
			kill -9 $NTP_Client_PID 2>/dev/null
		done
#}
