#!/bin/sh

if [ ! "$MTLK_INIT_PLATFORM" ]; then			
	. /tmp/mtlk_init_platform.sh
fi
print2log DBG "wave_wlan_wps_config: args: $*"
apIndex=$1

print2log DBG "running wave_wlan_wps_reset" 

$ETC_PATH/wave_wlan_wps_config $apIndex

print2log DBG "wave_wlan_wps_reset done" 
