#!/bin/sh

# Defines
if [ ! "$MTLK_INIT_PLATFORM" ]; then			
	. /tmp/mtlk_init_platform.sh
fi
apIndex=$1
#print2log DBG "running wave_wlan_get_ap_dyn_info" 
timestamp "wave_wlan_get_ap_dyn_info:$apIndex:begin"

# Get corresponding wlan network interface from mapping file
wlan=`find_wave_if_from_index $apIndex`

WLSEnabled=`host_api get $$ $apIndex WLSEnabled`
wlanInitIncomplete=`check_if_is_ready $wlan`
ifconfig_status=`ifconfig | grep $wlan`

if [ "$WLSEnabled" = "$NO" ] || [ "$wlanInitIncomplete" = "$YES" ] || [ "$ifconfig_status" = "" ]
then
	status=0
else
	status=1
	bssid=`iwconfig $wlan | grep Mode | cut -d ":" -f 3,4,5,6,7,8,9 | cut -d " " -f 2`
fi

echo "status=\"$status\""
echo "bssid=\"$bssid\""
   
#print2log DBG "wave_wlan_get_ap_dyn_info done" 

timestamp "wave_wlan_get_ap_dyn_info:$apIndex:done"
