#!/bin/sh

# Defines
if [ ! "$MTLK_INIT_PLATFORM" ]; then			
	. /tmp/mtlk_init_platform.sh
fi

apIndex=$1

print2log DBG "running wave_wlan_wps_trigger_pbc_pairing $1"

# Get corresponding wlan network interface from mapping file
wlan=`find_wave_if_from_index $apIndex`

echo "The button 'Start PBC' was activated for $wlan" > /dev/console

WPS_ON=`get_wps_on $apIndex $wlan`

if [ "$WPS_ON" = "$NO" ]
then
	print2log DBG "wave_wlan_wps_trigger_pbc_pairing: WPS disabled"
	return
fi

NETWORK_TYPE=`host_api get $$ $apIndex network_type`

#Note- apIndex is a number (not interface), in mtlk_wps_cmd.sh it is converted to proper wlan interface.
if [ "$NETWORK_TYPE" = "$STA" ]
then
	$ETC_PATH/mtlk_wps_cmd.sh get_conf_via_pbc 0
else
	$ETC_PATH/mtlk_wps_cmd.sh conf_via_pbc $apIndex
fi

print2log DBG "wave_wlan_wps_trigger_pbc_pairing done"
