#!/bin/sh

# Defines
if [ ! "$MTLK_INIT_PLATFORM" ]; then			
	. /tmp/mtlk_init_platform.sh
fi
print2log DBG "wlan_connect: args: $*"

$ETC_PATH/mtlk_init_wpa_supplicant.sh should_run && $ETC_PATH/mtlk_init_wpa_supplicant.sh create_config && $ETC_PATH/mtlk_init_wpa_supplicant.sh reload