#!/bin/sh

if [ ! "$MAPLOADED" ]; then
    if [ -r /tmp/wave300_map_apIndex ]; then
        . /tmp/wave300_map_apIndex 2>/dev/null
        MAPLOADED="1"
    fi
fi

# Source for common useful functions
if [ ! "$MTLK_INIT_PLATFORM" ]; then			
	. /tmp/mtlk_init_platform.sh
	MTLK_INIT_PLATFORM="1"
	print2log DBG "mtlk_init_platform called in wave_wlan_wps_trigger_pin_pairing"
fi
apIndex=$1
print2log DBG "running wave_wlan_wps_trigger_pbc_pairing $1"

#get corresponding wlan network interface from mapping file
eval wlan='$'w300_map_idx_${apIndex}
#wlan=wlan$1
echo "The button 'Start PBC' was activated for $wlan" > /dev/console

WPS_ON=`host_api get $$ $apIndex NonProc_WPS_ActivateWPS`

if [ "$WPS_ON" = "$NO" ]
then
	print2log DBG "wave_wlan_wps_trigger_pbc_pairing: WPS disabled"
	return
fi

$ETC_PATH/mtlk_wps_cmd.sh conf_via_pbc $apIndex

print2log DBG "wave_wlan_wps_trigger_pbc_pairing done" 
